# frozen_string_literal: true

module Retailers
  module Statistics
    # returns the turnover generated by users
    class SalesByUsersValueService
      def initialize(retailer, **args)
        @retailer = retailer
        @order = args[:order] == "ASC" ? "ASC" : "DESC"
        @limit = args[:limit]
      end

      def call!
        data = User.joins(receipts: :till).where(tills: {retailer: @retailer})
                   .group(:id)
                   .order("sum_receipts_amount_excluding_taxes_cents #{@order}")
                   .sum("receipts.amount_excluding_taxes_cents")

        data = data.first(@limit).to_h if @limit

        data
      end
    end
  end
end
